package com.example.demo.domain.mapper;

import com.example.demo.domain.model.UserRoleView;
import com.example.demo.domain.model.UserRoleViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserRoleViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role_view
     *
     * @mbg.generated
     */
    long countByExample(UserRoleViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role_view
     *
     * @mbg.generated
     */
    int deleteByExample(UserRoleViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role_view
     *
     * @mbg.generated
     */
    int insert(UserRoleView row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role_view
     *
     * @mbg.generated
     */
    int insertSelective(UserRoleView row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role_view
     *
     * @mbg.generated
     */
    List<UserRoleView> selectByExample(UserRoleViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role_view
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") UserRoleView row, @Param("example") UserRoleViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role_view
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") UserRoleView row, @Param("example") UserRoleViewExample example);
}